### ISSUE TITLE
Windows Defender automatically quarantines tier0.dll

### ISSUE THREAD

**Issue by woow101** [mastercomfig/tf2-patches#304]
### Description
Windows Defender quarantined tier0.dll, citing it to be a Trojan with the name "Win32/Azden.A!cl". Using "Learn more" opens to [this](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fAzden.A!cl&threatid=2147718745) malware description. I am fairly sure this is less of a bug and more of a Windows Defender mess up.

### Checklist
- [x] None of the open *or* closed issues document this problem.

### Screenshots
![image](https://user-images.githubusercontent.com/62764135/93947726-1c9c7900-fd02-11ea-8717-4baee34b0a68.png)

**Comment by Yttrium-tYcLief** [comment]
this sort of thing has been discussed in discord repeatedly; it's most likely just a heuristic detection, because it sees a modified version of a file that differs from the one that 99% of users have, so it flags it as suspicious and its default behavior towards suspicious files is to call them malicious. This is a common problem in the development world, and unfortunately there's not much we can do about it besides submit the file to Microsoft so that it gets certified as clean and doesn't get flagged again, which we've already done, but they're being awfully slow about it.

I'm going to leave this issue open so others can see it and not make duplicate issues, at least until we hear back from MS.

**Comment by joshuadinada** [comment]
> this sort of thing has been discussed in discord repeatedly; it's most likely just a heuristic detection, because it sees a modified version of a file that differs from the one that 99% of users have, so it flags it as suspicious and its default behavior towards suspicious files is to call them malicious. This is a common problem in the development world, and unfortunately there's not much we can do about it besides submit the file to Microsoft so that it gets certified as clean and doesn't get flagged again, which we've already done, but they're being awfully slow about it.
> 
> I'm going to leave this issue open so others can see it and not make duplicate issues, at least until we hear back from MS.

I mean, at least mention this in the installation guide so newcomers don't panic

**Comment by Yttrium-tYcLief** [comment]
I'll look into improving documentation tomorrow.

**Comment by henke37** [comment]
I hear that signing the files help with their reputation. And Valve sign everything they ship.

**Comment by UntouchedOdin0** [comment]
You can report the false report [here](https://www.microsoft.com/en-us/wdsi/filesubmission) I hope this helps. It might take a while for it to get checked over.
