### ISSUE TITLE
Add version_comtress command

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/tf2-patches#33]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am running older version of Team Comtress 2 and I do not know which one it is!

**Describe the solution you'd like**
A command like `version_comtress` which would return the current version of Team Comtress

**Describe alternatives you've considered**
Command can have other name

**Additional context**
Similar to `version_comfig` found in mastercomfig

**Comment by Yttrium-tYcLief** [comment]
Why not just bake this into `version`?

**Comment by micwoj92** [comment]
> Why not just bake this into `version`?

Maybe, this was inspired by version_comfig present in mastercomfig, therefore version_comtress.

**Comment by maximsmol** [comment]
Apologies, I thought there was no `version` command. We should add this

**Comment by int-72h** [comment]
This shouldn't take too long- I'll do it once linux builds are up.

**Comment by Yttrium-tYcLief** [comment]
Any implementation of this should also, ideally:

1. Modify `start_tf2.bat` to include `+version_comtress` or whatever command is eventually used
2. Include "dev" versus "release" variables, so that version_comtress only reports an actual release number if it's the public release build, built by Mastercoms, and just reports "debug" and a build timestamp otherwise
3. Implement this string as a variable that can be pulled by UI elements on the main menu, so that we can add a version indicator to the custom HUD

**Comment by micwoj92** [comment]
>     2. Include "dev" versus "release" variables, so that version_comtress only reports an actual release number if it's the public release build, built by Mastercoms, and just reports "debug" and a build timestamp otherwise

what about git commit sha?

**Comment by Yttrium-tYcLief** [comment]
Whatever you think is the best way to approach it, I have no problems. I just want to make sure we discern build versions from release versions.

**Comment by maximsmol** [comment]
Btw a hacky version to do this is literally adding `+alias comtress_version v1.0.0` or whatever to `start_tf2.bat`

**Comment by int-72h** [comment]
https://semver.org/ ideally we'd use semantic versioning but that's up to coms
